package cl.ipst.sca.frames;

import cl.ipst.sca.config.ConexionBBDD;
import cl.ipst.sca.model.Trabajador;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto Vargas Vargas <rvargas@dparica.cl>
 */
public class frmAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        miPanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Reportes = new javax.swing.JMenu();
        jmiAtrasos = new javax.swing.JMenuItem();
        jmiAdelantos = new javax.swing.JMenuItem();
        jmiInasistencias = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();
        jmiProbarConexion = new javax.swing.JMenuItem();
        jmiAyuda = new javax.swing.JMenuItem();
        jmiCerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout miPanelLayout = new javax.swing.GroupLayout(miPanel);
        miPanel.setLayout(miPanelLayout);
        miPanelLayout.setHorizontalGroup(
            miPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        miPanelLayout.setVerticalGroup(
            miPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );

        Reportes.setText("Reportes");

        jmiAtrasos.setText("Reporte de Atrasos");
        jmiAtrasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAtrasosActionPerformed(evt);
            }
        });
        Reportes.add(jmiAtrasos);

        jmiAdelantos.setText("Reporte de Salidas Tempranas");
        jmiAdelantos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdelantosActionPerformed(evt);
            }
        });
        Reportes.add(jmiAdelantos);

        jmiInasistencias.setText("Reporte de Inasistencias");
        jmiInasistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInasistenciasActionPerformed(evt);
            }
        });
        Reportes.add(jmiInasistencias);

        jMenuBar1.add(Reportes);

        Ayuda.setText("Ayuda");

        jmiProbarConexion.setText("Probar Conexión a BBDD");
        jmiProbarConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProbarConexionActionPerformed(evt);
            }
        });
        Ayuda.add(jmiProbarConexion);

        jmiAyuda.setText("Acerca de");
        jmiAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAyudaActionPerformed(evt);
            }
        });
        Ayuda.add(jmiAyuda);

        jMenuBar1.add(Ayuda);

        jmiCerrarSesion.setText("Cerrar Sesión");
        jmiCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiCerrarSesionMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmiCerrarSesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAtrasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAtrasosActionPerformed
        frmReporteAtrasos v = new frmReporteAtrasos();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiAtrasosActionPerformed

    private void jmiAdelantosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdelantosActionPerformed
        frmReporteSalidasAnt v = new frmReporteSalidasAnt();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiAdelantosActionPerformed

    private void jmiInasistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInasistenciasActionPerformed
        frmReporteInasistencias v = null;
        try {
            v = new frmReporteInasistencias();
        } catch (ParseException ex) {
            Logger.getLogger(frmAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiInasistenciasActionPerformed

    private void jmiAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAyudaActionPerformed
        ImageIcon icono = new ImageIcon(getClass().getResource("/cl/ipst/sca/resources/ipst.png"));
        String mensaje = "<html><div style='text-align: center;'>"
                + "<b>Sistema de Gestión de Asistencia</b><br>"
                + "<hr>"
                + "Programadores: <br>"
                + "Diego Troncoso <br>"
                + "Claudio Trigo <br>"
                + "Roberto Vargas <br>"
                + "<br>"
                + "Integración de Competencias II<br>"
                + "Instituto Profesional Santo Tomás - Sede Arica"
                + "</div></html>";

        JOptionPane.showMessageDialog(null, mensaje,
                "Sistema de Control de Asistencia", JOptionPane.INFORMATION_MESSAGE, icono);
    }//GEN-LAST:event_jmiAyudaActionPerformed

    private void jmiProbarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProbarConexionActionPerformed
        //Test de conexión
        ConexionBBDD conexion = new ConexionBBDD();
        conexion.probarConexion();
    }//GEN-LAST:event_jmiProbarConexionActionPerformed

    private void jmiCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiCerrarSesionMouseClicked
        int respuesta = JOptionPane.showConfirmDialog(
                null, // Componente padre
                "¿Desea cerrar sesión?", // Mensaje
                "Confirmación", // Título del diálogo
                JOptionPane.YES_NO_OPTION, // Tipo de opciones (Sí/No)
                JOptionPane.QUESTION_MESSAGE // Tipo de mensaje (pregunta)
        );
        if (respuesta == JOptionPane.YES_OPTION) {
            //Cerramos la ventana
            dispose();

            //Cerramos la sesión SINGLETON
            Trabajador.getInstancia().cerrarSesion();

            frmLogin v = new frmLogin();
            v.setSize(340, 400);
            v.setLocationRelativeTo(null);
            v.setVisible(true);
        }
    }//GEN-LAST:event_jmiCerrarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenu Reportes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiAdelantos;
    private javax.swing.JMenuItem jmiAtrasos;
    private javax.swing.JMenuItem jmiAyuda;
    private javax.swing.JMenu jmiCerrarSesion;
    private javax.swing.JMenuItem jmiInasistencias;
    private javax.swing.JMenuItem jmiProbarConexion;
    private javax.swing.JDesktopPane miPanel;
    // End of variables declaration//GEN-END:variables
}
