package cl.ipst.sca.frames;

import cl.ipst.sca.controllers.TrabajadorController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto Vargas Vargas <rvargas@dparica.cl>
 */
public class frmEliminarUsuario extends javax.swing.JInternalFrame {

    TrabajadorController trabajadorController = new TrabajadorController();

    public frmEliminarUsuario() throws SQLException {
        initComponents();
    }

    private void ClearAll() {
        txtRunBuscar.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloRegistrar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtRunBuscar = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTituloRegistrar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTituloRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRegistrar.setText("Deshabilitar Trabajador");

        btnBuscar.setText("Eliminar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel14.setText("Sin puntos ni dígito verificador.");

        jLabel1.setText("R.U.N.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRunBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTituloRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRunBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(
                null, // Componente padre
                "¿Está seguro de que desea deshabilitar el registro?", // Mensaje
                "Confirmación", // Título del diálogo
                JOptionPane.YES_NO_OPTION, // Tipo de opciones (Sí/No)
                JOptionPane.QUESTION_MESSAGE // Tipo de mensaje (pregunta)
        );
        if (respuesta == JOptionPane.YES_OPTION) {
            // Obtener el ID de cliente a buscar
            int runTrabajador;
            try {
                runTrabajador = Integer.parseInt(txtRunBuscar.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese un valor numérico válido para buscar", "Error de Validación", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Realizar la búsqueda del cliente
            Boolean res;
            try {
                res = trabajadorController.desactivarTrabajador(runTrabajador);
            } catch (SQLException ex) {
                Logger.getLogger(frmEliminarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                res = null;
            }

            // Mostrar resultados
            if (res != null) {
                JOptionPane.showMessageDialog(this, "Trabajador deshabilitado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                ClearAll();
            } else {
                // Si no se encontró el cliente, mostrar mensaje de error
                JOptionPane.showMessageDialog(this, "Trabajador no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTituloRegistrar;
    private javax.swing.JTextField txtRunBuscar;
    // End of variables declaration//GEN-END:variables
}
