package cl.ipst.sca.frames;

import cl.ipst.sca.controllers.TrabajadorController;
import cl.ipst.sca.controllers.TurnoController;
import cl.ipst.sca.controllers.CargoController;
import cl.ipst.sca.model.Cargo;
import cl.ipst.sca.model.Trabajador;
import cl.ipst.sca.model.Turno;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto Vargas Vargas <rvargas@dparica.cl>
 */
public class frmNuevoUsuario extends javax.swing.JInternalFrame {

    TrabajadorController trabajadorController = new TrabajadorController();
    TurnoController turnoController = new TurnoController();
    CargoController cargoController = new CargoController();

    Turno tAux = new Turno();
    Cargo cAux = new Cargo();

    public frmNuevoUsuario() throws SQLException {
        initComponents();
        cargarRegistros();
    }

    private void ClearAll() {
        txtNombres.setText(null);
        txtRUN.setText(null);
        txtDV.setText(null);
        txtNombres.setText(null);
        txtApellidos.setText(null);
        txtDepto.setText(null);
        txtArea.setText(null);
        txtCorreo.setText(null);
        txtClave.setText(null);
        cbbCargoID.setSelectedIndex(0);
        cbbTurnoID.setSelectedIndex(0);
    }

    private void cargarRegistros() throws SQLException {
        cbbCargoID.removeAllItems();
        cbbCargo.removeAllItems();
        cbbTurnoID.removeAllItems();
        cbbTurno.removeAllItems();

        int idTurno, idCargo;
        String datoTurno, datoCargo;

        List<Turno> listaTurnos = turnoController.listarTodosLosTurnos();
        for (int i = 0; i < listaTurnos.size(); i++) {
            tAux = listaTurnos.get(i);

            idTurno = tAux.getIdTurno();
            datoTurno = tAux.getDescripcionTurno() + " - " + tAux.getHoraIngreso() + " - " + tAux.getHoraSalida();

            cbbTurnoID.addItem(String.valueOf(idTurno));
            cbbTurno.addItem(datoTurno);
        }

        List<Cargo> listaCargos = cargoController.listarTodosLosCargos();
        for (int i = 0; i < listaCargos.size(); i++) {
            cAux = listaCargos.get(i);

            idCargo = cAux.getIdCar();
            datoCargo = cAux.getCargo();

            cbbCargoID.addItem(String.valueOf(idCargo));
            cbbCargo.addItem(datoCargo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloRegistrar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRUN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDepto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        btnGuardarCli = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbbCargo = new javax.swing.JComboBox<>();
        cbbTurno = new javax.swing.JComboBox<>();
        cbbCargoID = new javax.swing.JComboBox<>();
        cbbTurnoID = new javax.swing.JComboBox<>();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTituloRegistrar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTituloRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRegistrar.setText("Ingreso Nuevo Trabajador");

        jLabel2.setText("Nombres");

        jLabel3.setText("Apellidos");

        jLabel5.setText("R.U.N.");

        jLabel6.setText("DV");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("-");

        jLabel8.setText("Departamento");

        jLabel9.setText("Área");

        btnGuardarCli.setText("Guardar");
        btnGuardarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCliActionPerformed(evt);
            }
        });

        jLabel12.setText("Correo");

        jLabel13.setText("Clave");

        jLabel10.setText("Turno");

        jLabel11.setText("Cargo");

        cbbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        cbbCargo.setEnabled(false);

        cbbTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        cbbTurno.setEnabled(false);

        cbbCargoID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        cbbCargoID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbCargoIDItemStateChanged(evt);
            }
        });

        cbbTurnoID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        cbbTurnoID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbTurnoIDItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(177, 177, 177)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRUN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(txtDV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbbTurnoID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cbbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbbCargoID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cbbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnGuardarCli)
                                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTituloRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbTurnoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbCargoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(4, 4, 4)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(4, 4, 4)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarCli)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCliActionPerformed
        // Obtener los valores de los campos
        int run;
        char dv;
        int idCargo;
        int idTurno;
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText().trim();
        String departamento = txtDepto.getText().trim();
        String area = txtArea.getText().trim();
        String correo = txtCorreo.getText().trim();
        String clave = txtClave.getText().trim();

        String fullRUN = txtRUN.getText().trim() + "-" + txtDV.getText().trim().charAt(0);
        if (trabajadorController.validarRUT(fullRUN)) {
            // Manejar posibles excepciones con try-catch
            try {
                //id = Integer.parseInt(txtID.getText().trim());
                run = Integer.parseInt(txtRUN.getText().trim());
                dv = txtDV.getText().trim().charAt(0);
                idCargo = Integer.parseInt(cbbCargoID.getSelectedItem().toString());
                idTurno = Integer.parseInt(cbbTurnoID.getSelectedItem().toString());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error en formato de número", "Error de Validación", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Realizar validaciones restantes
            if (nombres.trim().isEmpty() || apellidos.isEmpty() || departamento.isEmpty() || area.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error de Validación", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Crear objeto Trabajador
            Trabajador t = new Trabajador();
            t.setRutTra(run);
            t.setDvTra(dv);
            t.setNombresTra(nombres);
            t.setApellidosTra(apellidos);
            t.setDepartamentoTra(departamento);
            t.setAreaTra(area);
            t.setCorreoTra(correo);
            t.setClaveTra(clave);

            Cargo newC = new Cargo();
            newC.setIdCar(idCargo);
            t.setCargoTra(newC);

            Turno newT = new Turno();
            newT.setIdTurno(idTurno);
            t.setTurnoTra(newT);

//         Intentar agregar el cliente usando el controlador
            boolean clienteAgregado;
            try {
                clienteAgregado = trabajadorController.agregarTrabajador(t);
            } catch (SQLException ex) {
                Logger.getLogger(frmNuevoUsuario.class.getName()).log(Level.SEVERE, null, ex);
                clienteAgregado = false;
            }

            // Mostrar mensaje de éxito o error
            if (clienteAgregado) {
                JOptionPane.showMessageDialog(this, "Trabajador agregado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                ClearAll();
            } else {
                JOptionPane.showMessageDialog(this, "Error al agregar el trabajador", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El RUN ingresado no es valido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarCliActionPerformed

    private void cbbTurnoIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbTurnoIDItemStateChanged
        if (evt.getStateChange() == evt.SELECTED) {
            int posicion = cbbTurnoID.getSelectedIndex();
            if (cbbTurno.getItemCount() > posicion) {
                cbbTurno.setSelectedIndex(posicion);
            }
        }
    }//GEN-LAST:event_cbbTurnoIDItemStateChanged

    private void cbbCargoIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbCargoIDItemStateChanged
        if (evt.getStateChange() == evt.SELECTED) {
            int posicion = cbbCargoID.getSelectedIndex();
            if (cbbCargo.getItemCount() > posicion) {
                cbbCargo.setSelectedIndex(posicion);
            }
        }
    }//GEN-LAST:event_cbbCargoIDItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCli;
    private javax.swing.JComboBox<String> cbbCargo;
    private javax.swing.JComboBox<String> cbbCargoID;
    private javax.swing.JComboBox<String> cbbTurno;
    private javax.swing.JComboBox<String> cbbTurnoID;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTituloRegistrar;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDV;
    private javax.swing.JTextField txtDepto;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtRUN;
    // End of variables declaration//GEN-END:variables
}
